os: osx
language: Swift
osx_image: xcode11.3
xcode_project: overwatch_league_iOS.xcodeproj
xcode_scheme: overwatch_league_iOS
xcode_destination: platform=iOS Simulator,OS=13.3,name=iPhone 11
env:
  global:
    - FRAMEWORK_NAME=Nimble.framework
    - FRAMEWORK_NAME=Quick.framework
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
  - carthage bootstrap
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
